### ISSUE TITLE
博主你好

### ISSUE THREAD

**Issue by Smecta** [xfg0218/greenplum--summarize#2]
是这样的 看到 你在csdn上发布了关于datacollector-ui的文章，看到评论说到 汉化参考，但是发现github 上早已不存在，请问还有方便发我当初3年前整理的文章吗？因为近期有所研究，谢谢博主

查看Blog地址:https://github.com/xfg0218/embrace-datacollector3.0.1,汉化请参考:https://github.com/xfg0218/embrace-datacollector3.0.1/blob/d7ee5743775cddf14fad2c031aa50b1e75317779/datacollector-ui/src/main/webapp--lixiaochuan/i18n/en.json3年前回复
![image](https://user-images.githubusercontent.com/30615458/103979974-e5bb7780-51b9-11eb-9b5d-a7bdd11dd7db.png)

**Comment by xfg0218** [comment]
你好，由于embrace-datacollector3.0.1项目涉及到敏感信息，先以删掉。更多资料可以参考streamsets官网:https://streamsets.com/tutorials/  教程，或者查看csdn的专栏:https://blog.csdn.net/xfg0218/category_7215586.html
